# Nihar Muniraju

 Load Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Creating a dataset

In [2]:
X,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=15)

In [3]:
X

array([[-0.3779567 ,  1.04389498,  1.04349443, ..., -0.0671922 ,
         0.17547148, -1.04964564],
       [-0.32525851,  1.27626282, -0.68612327, ...,  1.00663329,
        -0.83369182,  0.95774417],
       [ 0.73901891, -0.60090284, -0.17729436, ..., -0.21898072,
         0.87864296, -1.25774001],
       ...,
       [ 0.67556288, -0.53841971, -1.29950008, ...,  2.04333597,
         0.94738793,  0.79035376],
       [ 2.62971021, -2.45289885, -1.35978523, ...,  0.37889809,
        -1.97189411, -0.2522504 ],
       [-1.79149103, -0.12190773,  0.53515332, ..., -1.94135733,
         0.58900166, -1.00748218]])

# Converting the data to data frame

In [4]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -0.377957  1.043895  1.043494 -0.101838 -1.617442  0.402713  0.913601   
1   -0.325259  1.276263 -0.686123 -2.463205 -0.489426 -0.240715 -1.469496   
2    0.739019 -0.600903 -0.177294  1.335714 -0.817332 -0.790047  1.457365   
3    0.474312 -1.103002  1.189936 -0.800186  0.912377 -0.406451 -1.130950   
4    0.927365  1.114796  0.080284  1.261064  0.761179  0.921563  0.440832   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.538272  0.171629  0.075371 -0.957658 -1.066219  1.158096 -0.036964   
996 -0.060266  0.095018 -0.271685  1.830560  0.219445 -0.341269  1.180088   
997  0.675563 -0.538420 -1.299500  0.747835  1.733898 -0.268044 -0.520953   
998  2.629710 -2.452899 -1.359785  1.592065  0.854157  1.618828  0.621701   
999 -1.791491 -0.121908  0.535153 -0.588085 -1.929461 -0.659900  0.754921   

            7         8         9  
0   -0.067192  0.175471 -1.049646  
1    1.006633 -0.833692  0.957744  
2   -0.218981  0.878643 -1.257740  
3    1.985111  1.379029  1.041768  
4    0.184645 -1.567739 -0.142107  
..        ...       ...       ...  
995  0.123689  0.927871 -0.225003  
996 -0.216876 -1.752938 -0.810152  
997  2.043336  0.947388  0.790354  
998  0.378898 -1.971894 -0.252250  
999 -1.941357  0.589002 -1.007482  

[1000 rows x 10 columns]

In [5]:
y

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [6]:
X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size=0.30,random_state=42)

# implement logestic regression

In [7]:
log = LogisticRegression()


In [8]:
log.fit(X_train, y_train)

LogisticRegression()

In [9]:
y_pred = log.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [10]:
log.predict_proba(X_test) # for probaBILITY

array([[9.33104089e-01, 6.68959106e-02],
       [6.59976832e-01, 3.40023168e-01],
       [8.65439561e-01, 1.34560439e-01],
       [9.59081747e-02, 9.04091825e-01],
       [2.43108150e-01, 7.56891850e-01],
       [5.76396931e-01, 4.23603069e-01],
       [8.25188888e-01, 1.74811112e-01],
       [2.29999952e-04, 9.99770000e-01],
       [1.25363187e-02, 9.87463681e-01],
       [2.73346597e-03, 9.97266534e-01],
       [7.06227890e-03, 9.92937721e-01],
       [5.68134296e-01, 4.31865704e-01],
       [8.38796778e-02, 9.16120322e-01],
       [9.73835584e-01, 2.61644162e-02],
       [1.27501162e-02, 9.87249884e-01],
       [8.06120072e-01, 1.93879928e-01],
       [9.95125747e-01, 4.87425270e-03],
       [1.78699988e-02, 9.82130001e-01],
       [9.78717701e-01, 2.12822989e-02],
       [3.90303620e-02, 9.60969638e-01],
       [3.39139480e-02, 9.66086052e-01],
       [3.13743686e-02, 9.68625631e-01],
       [5.00274883e-02, 9.49972512e-01],
       [8.18573651e-01, 1.81426349e-01],
       [8.590384

In [11]:
score =accuracy_score (y_test,y_pred)
print("score", score)
confusion = confusion_matrix(y_test,y_pred)
print("confusion", confusion)

print(classification_report(y_test,y_pred))

score 0.9166666666666666
confusion [[146  11]
 [ 14 129]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



# Hyperparameter Tuning And Cross Validation

In [12]:
model = LogisticRegression()
penality =['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

# to put all the above values in the key value pair

In [13]:
params=dict(penalty=penality,C=c_values,solver=solver)
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

# Grid search  CV

In [14]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [15]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [16]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [17]:
grid.fit(X_train,y_train)

c:\Users\nihar\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\nihar\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\nihar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nihar\anaconda3\Lib\site-packages\sklearn\linear_model\_

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')